"""Initial migration

Revision ID: 596e738b0acd
Revises: 
Create Date: 2025-08-02 15:39:11.943510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596e738b0acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('CEO', 'STOREKEEPER', 'SELLER', 'PURCHASER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
